version: '3' #1
services: #2
  app: #3
    container_name: react-app-container #4
    image: node:16-alpine #5
    volumes:
      - ./:/app #6
    working_dir: /app #7
    command: sh -c "npm install && npm run dev" #8
    ports:
      - '3000:3000' #9
